### ISSUE TITLE
Issue with FritzBox 7530 and OS 7.50

### ISSUE THREAD

**Issue by begra** [puschie286/fritzbox-bridge#35]
Are there any known issues with FritzOS 7.50? 
Before the update everything worked without problems. Since the update, the trigger for the "device connection" / "device disconnection" unfortunately no longer works. I have checked the device name. Login is also ok according to settings.

**Comment by puschie286** [comment]
not yet - it is mentioned in one review that is doesnt work. you might try the test version v0.9.1 - this version use a different approach for network device detection so this could solve the problem ( my own fritzbox doesnt support 7.5 yet so i cannot test it ).
this test version also include a debug button on the settings menu that will send some debug information to me - if you still have problems, i would like you to send me the debug information using this button

**Comment by puschie286** [comment]
unfortunately, the button only send dect device informations because all other data contain highly sensitive informations about your internal network.

to progress here, i need this network data^^ - you could grab it by yourself. 
Open your fritzbox website, login, go to network under home. open your console (F12) on this page and go to network - there should be some entries with file/name „data.lua“ of type „json“ or „xhr“. click on one of them an go to „response“ - this is the data i need ( and the data my app use to determine connect/disconnect ). 

Please send it to my email ( christoph286@googlemail.com )

**Comment by begra** [comment]
Thank you for the explanation. I have just sent the mail.

**Comment by puschie286** [comment]
thanks, checked it but didnt find anything problematicly - i will need to find a way for futher investigation, keep you up to date

**Comment by begra** [comment]
Since updating to 0.9.3 it works fine again. Thanks for the quick help!
